### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by LegitCodeRed** [teamb58/WhatsAppB58edition#1]
Can you please specify how to compile and edit this?
Cause I can't find a soloution. I would highly appreciate this. 

Have a great day

**Comment by teamb58** [comment]
Sure. Follow the following steps. 
Download the project and extract the contents to a folder.
Open it with Android Studio.
Wait for it to sync.
Do the necessary changes.
Use build option to build the apk.

That's it.

**Comment by LegitCodeRed** [comment]
Thank you but,
I tried that but i does not sync I get this error:
Gradle sync failed: Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Im sorry for any trouble btw

**Comment by teamb58** [comment]
You have to update your gradle and other dependencies.
Then it will work.
