### ISSUE TITLE
com.whatsapp.ow

### ISSUE THREAD

**Issue by jespra** [teamb58/WhatsAppB58edition#2]
Hi!,
I have an issues in some class, and it's say that 

com.whatsapp.ow is not public in com.whatsapp. Cannot be access from outside the package

And that

There is not default constructor avalible  in com.whatsapp.ow has no

can you help me?

**Comment by teamb58** [comment]
Which base of whatsapp are you trying to use it on? Where exactly is this error occurring?

**Comment by teamb58** [comment]
Closing this issue as no proper information is provided.
