### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by AviFix** [teamb58/WhatsAppB58edition#4]
Hi

Can you please update to the last WhatsApp version?

Thanks

**Comment by teamb58** [comment]
Hi,
Thanks for still following the project. I have actually discontinued work on this main version and am currently maintaining only mini version.
Please let me know the problems you are facing and I will try to help.

**Comment by AviFix** [comment]
What is the mini version?

**Comment by teamb58** [comment]
> What is the mini version?

It's a lite version with just privacy and status download feature.

**Comment by teamb58** [comment]
Happy to announce that we are planning to resume work soon.

Stay tuned.

TeamB58.
