### ISSUE TITLE
Compiled version apk

### ISSUE THREAD

**Issue by rizwansoaib** [teamb58/WhatsAppB58edition#5]
Can you please share apk files before work start on project I want confirm is this project really working as of 2020 or not.

Thank you for your project

**Comment by teamb58** [comment]
Hi,
Yes it supports latest version of WhatsApp. It is just that you have to adjust the calling methods and other files as per the base you use.
Not sure what apk you're asking.

**Comment by teamb58** [comment]
Closing this as there is no reply from user.
